[package]
name = "metabricks_nft_contract"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
solana-program = "1.8.0"
mpl-token-metadata = "3.2.0"
spl-token = "4.0.0"
spl-associated-token-account = "2.2.0"
